# Where things are
source:       .
destination:  ./_site
plugins:      ./_plugins
layouts:      ./_layouts
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     kramdown
highlighter:  pygments
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null


#Site config
title: cherryz's blog
description: 我的技术博客
keywords: Linux SBC OS Windows MacOSX ARM Raspberry Pi AVR Arduino
url: https://cherryz.github.io/
feed: /atom.xml
favicon: http://jekyllrb.com/favicon.png

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 分类目录
    url: /categories.html
  - text: 文章归档
    url: /archives.html
  - text: 联系我
    url: /contact.html
  - text: 友情链接
    url: /links.html

#Author config
author:
    name: cherryz
    email: chengweizhu.zjzs@gmail.com
    imageLink: https://avatars3.githubusercontent.com/u/3377611?v=3&s=460
    simpleIntro: 我是「cherryz」，技术宅一个。
    detailIntro:
      <p>我是「cherryz」，技术宅一个。平时除了正常的上下班，其它时间都是在折腾跟技术有关的东西。</p>
      <p>2007年真正开始自学电脑，当时对好多东西都感兴趣，比如PS、网页制作、Windows操作系统、.Net技术以及Windows AIK等。在此得感谢我的母校（哈尔滨工程大学），学校的图书馆计算机方面的书籍特别丰富，也特别新，印象特别深刻的是当时Silverlight刚出，学校图书馆就有这个书了。用现在的话说，当时的我是一个彻彻底底的微软粉，只要微软出个新东西，我就去了解。由于同学的电脑大部分都是Windows系统，所以之后的大部分时间我便成了我们班里的“网管”，有事没事给人弄弄电脑。平时很大一部分时间，我也是泡在Windows系统群、远景论坛等。</p>
      <p>大概是在2008年的时候，接触了一个叫做ubuntu的系统。说实话，当时是被其华丽的UI给吸引的。虽然，当时安装的时候吃了很多苦头（当时笔记本安装ubuntu8.04，驱动问题真是头疼），在加上国内好多源速度都是出奇的慢，安装一个系统（加上update和upgrade）得花我一下午时间，还有学校的有线网络（锐捷客户端），更是搞得我放弃。所以之后的很长一段时间，ubuntu系统一直是存活在我的vm中，物理机始终是我熟悉的Windows。</p>
      <p>2010年工作以后，有了新电脑，linux也因为ubuntu的系统的易用以及微软开始打压盗版系统变得普及，似乎不那么的让人害怕，在加上之前的虚拟机体验，多多少少对linux也有了一些了解，于是又开始了我的linux折腾之路，直到现在linux已基本满足我的日常使用（debian）。当然，后来又增添了Mac OS X。</p>
      <p>总结一下吧，对于我这个外行的人看来，linux的使用让我对底层有了些认识，也让我体验到了源的好处。虽然在易用性上仍需努力，但是，好多理念仍是值得微软学习。好吧，就写这么多，目前，对嵌入式这一块很感兴趣，有兴趣的同学一起交流，多多指导。</p>

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: fa fa-rss
    url: /atom.xml
  - class: fa fa-weibo
    url: http://weibo.com/chengweibaby
  - class: fa fa-github-alt
    url: http://github.com/cherryz
  - class: fa fa-google-plus
    url: https://plus.google.com/115485206454521306575

#Links
customLinks:
  - item:
    - text: cnBeta
      url: http://www.cnbeta.com/
    - text: solidot
      url: http://www.solidot.org/
    - text: Xmodulo
      url: http://xmodulo.com/
    message: IT News
  - item:
    - text: debian
      url: https://www.debian.org/
    - text: WikiDevi
      url: https://wikidevi.com/wiki/Main_Page
    - text: eLinux
      url: http://elinux.org/Main_Page
    message: 嵌入式相关

#googleAnaly, your id link UA-12345678-X
googleAnaly:
  config: false
  id:

#comment config
disqus:
  config: false
  id:

duoshuo:
  config: true
  id: cherryz
